'use strict';
let state, busy=false, feedbackTimer;
const $=s=>document.querySelector(s);
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={leaf:'<path d="M20 4C9 2 3 8 5 15s14 5 15-11Z"/><path d="m4 21 10-12"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',list:'<path d="M9 5h11M9 12h11M9 19h11M3 5h1M3 12h1M3 19h1"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18"/>',settings:'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="9" cy="18" r="2"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',arrow:'<path d="M4 12h16m-5-5 5 5-5 5"/>',check:'<path d="m5 12 4 4L19 6"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.leaf}</svg>`;
const time=n=>new Intl.DateTimeFormat('en-CA',{hour:'numeric',minute:'2-digit',timeZone:state.plan.zone}).format(n);
const date=n=>new Intl.DateTimeFormat('en-CA',{month:'short',day:'numeric',timeZone:state.plan.zone}).format(n);
const fullDate=n=>new Intl.DateTimeFormat('en-CA',{weekday:'long',month:'long',day:'numeric',timeZone:state.plan.zone}).format(n);
const localInput=n=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:state.plan.zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(n).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;};
const btn=(label,action,cls='',extra='')=>`<button class="btn ${cls}" data-action="${action}" ${extra}>${label}</button>`;
const page=()=>['today','plan','connections','preferences'].includes(location.hash.slice(1))?location.hash.slice(1):'today';
function feedback(message){clearTimeout(feedbackTimer);$('#feedback').textContent=message;feedbackTimer=setTimeout(()=>$('#feedback').textContent='',7000);}
async function load(){const r=await fetch('/api/state');if(!r.ok)throw Error('The local server is unavailable. Restart it and refresh.');state=await r.json();render();}
function render(){
 const p=state.plan,current=page();
 const nav=[['today','Today','sun'],['plan','Your plan','list'],['connections','Connections','calendar'],['preferences','Preferences','settings']];
 $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">${icon('leaf')}</div><div><div class="brand-name">AI Mood Checker</div><div class="brand-sub">A little more room.</div></div></div><nav class="nav" aria-label="Main navigation">${nav.map(([id,label,i])=>`<a href="#${id}" ${current===id?'aria-current="page"':''}>${icon(i)}${label}</a>`).join('')}</nav><div class="sidebar-foot">${icon('leaf')}<p>Your day can change.<br>Your plan can, too.</p></div></aside><main id="main" class="workspace" tabindex="-1"><div class="topbar"><span>${h(fullDate(state.now))} · ${h(time(state.now))}${p.demo?' · Sample clock':''}</span><span class="status-label">${p.demo?'Sample calendar':p.connection==='connected'?'Google Calendar connected':'Calendar '+h(p.connection)}</span></div>${({today:today,plan:planPage,connections:connections,preferences:preferences})[current]()}</main></div>`;
}
function heading(title,description){return `<header class="heading"><h1>${title}</h1><p>${description}</p></header>`;}
function demoBanner(){if(!state.plan.demo)return '';const changed=state.plan.events.some(e=>e.id==='shift'&&e.etag==='2');return `<div class="demo-banner"><p><strong>Try a sample day.</strong> ${changed?`Your shift ran late. Your chosen window is ${state.plan.availableMinutes} minutes.`:'A café shift, a report due tonight, and a plan that can change.'}<br>Everything here is synthetic. No account needed.</p>${btn(changed?'Replay sample':'Try a late shift',changed?'reset':'shift','',changed?'':`aria-label="Try a late shift"`)}</div>`;}
function today(){const p=state.plan,r=state.result;return `${heading(p.reason.includes('shift ended')?'Your day changed. You’ve got options.':'One next step. A little more room.',h(p.reason))}${demoBanner()}<div class="today-grid"><div><section class="capacity" aria-labelledby="capacity-title"><h2 id="capacity-title">How much time do you have?</h2><div class="capacity-options">${[10,20,40,60].map(n=>`<button class="chip" data-action="capacity" data-minutes="${n}" aria-pressed="${p.availableMinutes===n}">${n} min</button>`).join('')}</div><div class="energy-row"><label for="energy">Energy, if you want to share</label><select id="energy" aria-label="Available energy"><option value="any" ${p.energy==='any'?'selected':''}>No preference</option><option value="low" ${p.energy==='low'?'selected':''}>Keep it light</option><option value="focused" ${p.energy==='focused'?'selected':''}>Ready to focus</option></select></div></section>${actionCard()}${r.warnings.length?`<aside class="warning"><strong>A quick reality check</strong>${r.warnings.map(w=>`<p>${h(p.tasks.find(t=>t.id===w.taskId)?.title)}: ${h(w.message)}</p>`).join('')}</aside>`:''}<div class="bottom-note">${icon('shield')}<span>Mood check-ins are optional. Your plan stays on this computer.</span></div></div><aside class="rail">${schedule()}${remaining()}${inbox()}</aside></div>`;}
function actionCard(){const p=state.plan;const accepted=p.sessions.find(s=>s.status==='planned');const needsReview=p.sessions.filter(s=>s.status==='needs-review');const s=state.result.suggestion;
 if(accepted)return `<section class="panel action-card"><div class="action-meta"><span class="pill">Your accepted action</span><span class="duration">${icon('clock')}${accepted.minutes} min</span></div><h2>${h(accepted.title)}</h2><p class="task-context">${h(p.tasks.find(t=>t.id===accepted.taskId)?.title)}</p><div class="action-facts"><span>${icon('clock')}${h(time(accepted.start))} – ${h(time(accepted.end))}</span></div><div class="actions">${btn(icon('check')+' Mark done','complete','primary',`data-id="${h(accepted.id)}"`)}${btn('Skip for now','skip','',`data-id="${h(accepted.id)}"`)}</div><div class="explain">Time passing doesn’t mark this complete. Let us know when you’ve done it.</div></section>`;
 const previous=needsReview.length?`<div class="warning"><strong>Your previous action needs a new time.</strong>${needsReview.map(x=>`<p>${h(x.title)}</p><div class="actions">${btn('I already did it','complete','quiet',`data-id="${h(x.id)}"`)}${btn('Skip old session','skip','quiet',`data-id="${h(x.id)}"`)}</div>`).join('')}</div>`:'';
 if(!s)return `${previous}<section class="panel action-card empty"><div class="eyebrow">A plan that fits</div><h2>${p.tasks.length?'Let’s make a little more room.':'Start with one thing.'}</h2><p>${h(state.result.message)}</p><div class="actions"><a class="btn quiet" href="#plan">Open your plan ${icon('arrow')}</a></div></section>`;
 return `${previous}<section class="panel action-card"><div class="action-meta"><span class="pill">A good next step</span><span class="duration">${icon('clock')}${s.minutes} min</span></div><h2>${h(s.title)}</h2><p class="task-context">${h(s.taskTitle)}</p><div class="action-facts"><span>${icon('clock')}${h(time(s.start))} – ${h(time(s.end))}</span><span>${icon('calendar')}Due ${h(date(s.deadline))}, ${h(time(s.deadline))}</span></div><div class="actions">${btn('Make this my next step '+icon('arrow'),'accept','primary',`data-id="${h(s.id)}"`)}</div><div class="secondary-actions">${btn('I have less time','less','quiet')}${btn('Another suggestion','dismiss','quiet',`data-id="${h(s.id)}"`)}</div><details class="explain"><summary>Why this step?</summary><p>${h(s.explanation)}</p><p>It’s one part of the assignment. Accepting it doesn’t finish the whole task or change your calendar.</p>${btn('Dismiss for now','dismiss','quiet',`data-id="${h(s.id)}"`)}</details></section>`;
}
function schedule(){const p=state.plan;const events=[...p.events.map(e=>({...e,kind:'event'})),...p.sessions.filter(s=>s.status==='planned').map(s=>({...s,kind:'session'}))].filter(e=>localInput(e.start).slice(0,10)<=localInput(state.now).slice(0,10) && localInput(e.end-1).slice(0,10)>=localInput(state.now).slice(0,10)).sort((a,b)=>a.start-b.start);return `<section><div class="section-title"><h2>The rest of your day</h2><a href="#connections">${p.demo?'Sample calendar':'Sync status'}</a></div><div class="timeline">${events.length?events.map(e=>`<div class="event ${e.end<state.now?'past':''} ${e.id==='shift'&&e.etag==='2'||e.kind==='session'?'highlight':''}"><div class="event-time">${h(time(e.start))}</div><div class="event-content"><strong>${h(e.title)}</strong><small>Until ${h(time(e.end))} · ${e.kind==='session'?'Your plan':e.source==='google'?'Google Calendar':'Sample event'}</small>${e.id==='shift'&&e.etag==='2'?'<br><span class="inline-tag">Ended 35 min later</span>':''}</div></div>`).join(''):'<p class="note">No events in today’s saved calendar.</p>'}</div></section>`;}
function remaining(){return `<section><hr class="rule"><div class="section-title"><h2>Still on your plate</h2><a href="#plan">See your plan</a></div>${state.plan.tasks.filter(t=>t.remaining!==0).map(t=>`<div class="mini-task"><strong>${h(t.title)}</strong><div class="meta"><span>Due ${h(date(t.deadline))}</span><span>${t.remaining===null?'Estimate needed':`${t.remaining} min left`}</span></div></div>`).join('')||'<p class="note">Nothing waiting. Add a task when you’re ready.</p>'}<p class="note">Remaining time is your estimate, not a promise that everything fits.</p></section>`;}
function inbox(){const jobs=state.plan.jobs.filter(j=>j.status==='inbox');return jobs.length?`<section class="inbox"><div class="section-title"><h2>Planning inbox</h2><span class="small">In-app only</span></div>${jobs.slice(-3).reverse().map(j=>`<div class="note">${j.version===state.plan.version?'Your plan may need a moment. Open Today for the current suggestion.':'An earlier prompt has expired. Today shows your current plan.'}<br>${h(time(j.delivered))} · ${state.plan.demo?'Simulated reminder':'Local reminder'}</div>`).join('')}${btn('Snooze for 1 hour','snooze','quiet')}</section>`:'';}
function taskForm(t){const id=t?.id||'',tag=h(id||'new');return `<form data-form="task" data-id="${h(id)}" class="form-section"><div class="form-error" role="alert"></div><div class="field"><label for="title-${tag}">Task title</label><input id="title-${tag}" name="title" required maxlength="160" value="${h(t?.title||'')}" placeholder="e.g. Research methods report"></div><div class="forms-grid"><div class="field"><label for="deadline-${tag}">Deadline (${h(state.plan.zone)})</label><input id="deadline-${tag}" type="datetime-local" name="deadline" required value="${t?localInput(t.deadline):localInput(state.now+86400000)}"></div><div class="field"><label for="remaining-${tag}">Remaining effort, in minutes</label><input id="remaining-${tag}" type="number" name="remaining" min="1" max="10080" value="${t?.remaining??''}" placeholder="Leave blank if unknown"><small>Includes all unfinished steps.</small></div></div><button class="btn primary" type="submit">${t?'Save changes':'Add task'}</button></form>`;}
function stepForm(t){const tag=h(t.id);return `<form data-form="step" data-id="${tag}" class="form-section"><div class="form-error" role="alert"></div><div class="field"><label for="step-${tag}">A specific next step you can confirm</label><input id="step-${tag}" name="title" required maxlength="160" placeholder="e.g. Outline the three key findings"></div><div class="forms-grid"><div class="field"><label for="minutes-${tag}">Your estimate, in minutes</label><input id="minutes-${tag}" name="minutes" required type="number" min="1" max="180" value="20"></div><div class="field"><label for="step-energy-${tag}">Energy needed</label><select id="step-energy-${tag}" name="energy"><option value="low">Light effort</option><option value="focused">Focused effort</option></select></div></div><button class="btn primary" type="submit">Confirm this step</button></form>`;}
function planPage(){const p=state.plan;return `${heading('A little structure. Room to adjust.','Keep the list short. Give each task an honest estimate and at least one confirmed next step.')}<div class="page-column"><div class="task-list">${p.tasks.map(t=>`<section class="panel"><div class="task-row-top"><div><h2>${h(t.title)}</h2><small>Due ${h(date(t.deadline))} at ${h(time(t.deadline))}</small></div><div class="task-estimate">${t.remaining===null?'Estimate needed':t.remaining===0?'Completed':`${t.remaining} min remaining`}</div></div><ul class="step-list">${t.steps.map(s=>`<li class="${s.done?'done':''}"><span>${s.done?'Done · ':''}${h(s.title)}${s.dependsOn.length?' · after prior step':''}</span><span>${s.minutes} min</span></li>`).join('')}</ul>${t.remaining===0?'':`<details><summary>Add a confirmed step</summary>${stepForm(t)}</details><details><summary>Edit task or deadline</summary>${taskForm(t)}</details>`}</section>`).join('')}</div><section class="panel"><h2>Add one thing</h2><p>A calendar tells us when you’re busy. You supply the task, deadline and effort estimate.</p>${taskForm()}</section></div>`;}
function connections(){const p=state.plan;return `${heading('Your calendar. A clearer picture.','Read-only access helps your plan adapt to changes. It never edits your Google events.')}<div class="page-column"><section class="panel"><h2>Google Calendar</h2><p>Connect your primary calendar to bring in busy times for the next 14 days. Recurring events are expanded by Google; cancelled, declined and “free” events don’t block your time.</p><dl class="connection-facts"><div><dt>Connection</dt><dd>${p.demo?'Sample data only':h(p.connection)}</dd></div><div><dt>Last successful sync</dt><dd>${p.lastSync?`${h(date(p.lastSync))}, ${h(time(p.lastSync))}${p.demo?' (sample)':''}`:'Not yet synced'}</dd></div><div><dt>Checks for changes</dt><dd>Every 5 minutes while the local server runs</dd></div><div><dt>Sign-in</dt><dd>${state.googleConfigured?'Google OAuth client configured':'OAuth client setup needed'}</dd></div></dl>${p.demo?`<p>Start your own empty plan before importing personal events. This clears the sample tasks and responses.</p>${btn('Start my own plan','clear','primary')}`:state.googleConnected?`<div class="actions">${btn('Sync now','google-sync','primary')}${btn('Disconnect','google-disconnect')}</div>`:`<div class="actions">${btn('Connect Google Calendar','google-connect','primary')}</div>`}${!state.googleConfigured?'<p class="note">The local server needs GOOGLE_CLIENT_ID and, if supplied by Google, GOOGLE_CLIENT_SECRET from a Desktop OAuth client with the Calendar API enabled. Your app’s setup guide covers this. No credentials belong in this page.</p>':''}</section><section class="panel"><h2>What the connection can tell us</h2><p>Events supply busy times, titles and source identifiers. They don’t supply assignment instructions or reliable effort estimates. Add those in Your plan.</p><p>If a sync fails, your last calendar stays visible and suggestions pause until a successful sync. Sign-in tokens are kept in memory; reconnect after restarting the server.</p><p class="note">This is a local, single-person prototype. Phone push delivery and a hosted multi-user release are still pending.</p></section></div>`;}
function preferences(){const p=state.plan,f=p.preferences;return `${heading('Make a little room for yourself.','Choose what the planner knows and when it can ask for your attention.')}<div class="page-column"><section class="panel"><h2>Planning preferences</h2><form data-form="preferences"><div class="form-error" role="alert"></div><div class="forms-grid"><div class="field"><label for="zone">Your timezone</label><input id="zone" name="zone" required value="${h(p.zone)}"><small>Use a timezone such as America/Vancouver.</small></div><div class="field"><label for="buffer">Buffer around events, in minutes</label><input id="buffer" name="buffer" type="number" min="0" max="30" required value="${p.bufferMinutes}"></div></div><label class="check-field"><input name="reminders" type="checkbox" ${f.reminders?'checked':''}><span>Allow planning prompts in the local inbox<small>Saved on the server. No phone push notifications are sent.</small></span></label><label class="check-field"><input name="paused" type="checkbox" ${f.paused?'checked':''}><span>Pause all prompts</span></label><div class="forms-grid"><div class="field"><label for="quietStart">Quiet hours start (0–23)</label><input id="quietStart" name="quietStart" type="number" min="0" max="23" required value="${f.quietStart}"></div><div class="field"><label for="quietEnd">Quiet hours end (0–23)</label><input id="quietEnd" name="quietEnd" type="number" min="0" max="23" required value="${f.quietEnd}"></div><div class="field"><label for="dailyLimit">Maximum prompts per day</label><select id="dailyLimit" name="dailyLimit">${[1,2,3].map(n=>`<option value="${n}" ${f.dailyLimit===n?'selected':''}>${n}</option>`).join('')}</select></div></div><div class="actions"><button class="btn primary" type="submit">Save preferences</button>${btn('Snooze for 1 hour','snooze')}</div></form></section><section class="panel"><h2>Your data, on your terms</h2><p>This planner uses its own local database. Your original desktop mood journal is kept separate. No journal history is imported, and this prototype makes no AI requests.</p><div class="actions"><a class="btn" href="/api/export" download>Export your plan</a>${btn('Delete planner data','clear','danger')}${btn('Load sample day','reset','quiet')}</div>${p.demo?`<div class="explain"><p>Sample time is fixed so you can replay the same scenario. Advance it to test expired suggestions and reminder timing.</p>${btn('Advance sample clock 10 min','advance','quiet')}</div>`:''}</section></div>`;}
async function act(payload,form){
 if(busy)return;busy=true;clearTimeout(feedbackTimer);$('#feedback').textContent=payload.action==='google-sync'?'Syncing Google Calendar…':'Saving…';document.querySelectorAll('button').forEach(b=>b.disabled=true);
 try {const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Planner-Token':state.csrf},body:JSON.stringify(payload)});let data;try{data=await r.json();}catch{throw Error('The server returned an unreadable response. Please reload.');}if(!r.ok)throw Error(data.error||'Could not save. Please try again.');if(data.url){location.assign(data.url);return;}await load();feedback(({accept:'Your next step is saved.',complete:'Done. Your remaining work is updated.',skip:'Skipped. Nothing was marked complete.',preferences:'Preferences saved.',task:'Task saved.',step:'Step confirmed.',clear:'Your planner data was cleared.',reset:'Sample day loaded.',snooze:'Prompts snoozed for one hour.','google-sync':'Calendar synced.'})[payload.action]||'Plan updated.');}
 catch(e){if(form){const box=form.querySelector('.form-error');box.textContent=e.message;box.tabIndex=-1;box.focus();}else{if(['accept','complete','skip'].includes(payload.action))await load().catch(()=>{});feedback(e.message);}}
 finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;
 if(['clear','reset'].includes(action)&&!confirm(action==='clear'?'Clear all planner tasks, imported events, responses and preferences on this computer? Your desktop journal stays intact.':'Replace this planner’s data with the synthetic sample day? Export first if you want to keep it.'))return;
 const payload={action,id:b.dataset.id||''};if(action==='capacity'){payload.minutes=Number(b.dataset.minutes);payload.energy=state.plan.energy;}if(action==='less'){payload.action='capacity';payload.minutes=state.plan.availableMinutes>20?20:10;payload.energy=state.plan.energy;}
 act(payload);
});
document.addEventListener('change',e=>{if(e.target.id==='energy')act({action:'capacity',minutes:state.plan.availableMinutes,energy:e.target.value});});
document.addEventListener('submit',e=>{const form=e.target;if(!form.matches('[data-form]'))return;e.preventDefault();const f=new FormData(form),action=form.dataset.form,payload={action};
 if(action==='task')Object.assign(payload,{id:form.dataset.id,title:f.get('title'),deadline:f.get('deadline'),remaining:f.get('remaining')===''?null:Number(f.get('remaining'))});
 if(action==='step')Object.assign(payload,{taskId:form.dataset.id,title:f.get('title'),minutes:Number(f.get('minutes')),energy:f.get('energy')});
 if(action==='preferences')Object.assign(payload,{zone:f.get('zone'),buffer:Number(f.get('buffer')),reminders:f.has('reminders'),paused:f.has('paused'),quietStart:Number(f.get('quietStart')),quietEnd:Number(f.get('quietEnd')),dailyLimit:Number(f.get('dailyLimit'))});
 act(payload,form);
});
window.addEventListener('hashchange',()=>{if(state){render();$('#main').focus({preventScroll:true});window.scrollTo(0,0);}});
window.addEventListener('focus',()=>{if(state&&!busy&&!document.activeElement?.matches('input,select'))load().catch(()=>{});});
load().catch(e=>{$('#app').innerHTML=`<main class="loading"><h1>Your plan is taking a moment.</h1><p>${h(e.message)}</p><a class="btn" href="/">Try again</a></main>`;});
